version: 2
registries:
  npm-registry-npm-tillersystems-com:
    type: npm-registry
    url: https://npm.tillersystems.com
    token: "${{secrets.NPM_REGISTRY_NPM_TILLERSYSTEMS_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  labels:
  - dependencies update
  - dependabot
  - need review
  versioning-strategy: increase
  ignore:
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: framer-motion
    versions:
    - 3.1.1
    - 3.2.1
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
    - 3.9.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: "@storybook/theming"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: ini
    versions:
    - 1.3.7
    - 1.3.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.5
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.1
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.13.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
  - dependency-name: "@babel/plugin-external-helpers"
    versions:
    - 7.12.1
  - dependency-name: markdown-to-jsx
    versions:
    - 6.11.4
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-transform-modules-commonjs"
    versions:
    - 7.12.1
    - 7.13.0
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: luxon
    versions:
    - 1.25.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: "@storybook/addon-info"
    versions:
    - 5.3.21
  - dependency-name: elliptic
    versions:
    - 6.5.3
  registries:
  - npm-registry-npm-tillersystems-com
