# Tiller - Stardust
# This configuration file is part of Tiller Stardust

version: 2

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# REFERENCES
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

references:
  workspace_root: &workspace_root /home/circleci/tiller-workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_deps_cache: &restore_deps_cache
    restore_cache:
      keys:
        - deps-{{ checksum "yarn.lock" }}

  save_deps_cache: &save_deps_cache
    save_cache:
      key: deps-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

  install_pip: &install_pip
    run:
      name: Installing pip
      command: sudo apt-get install python-pip

  install_awscli: &install_awscli
    run:
      name: Install AWS CLI
      command: sudo pip install awscli

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# DEFAULTS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: circleci/node:14.16.0

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# JOBS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

jobs:
  # Sets up the environment: checks out the code and installs dependencies.
  setup:
    <<: *defaults
    steps:
      - checkout
      - *restore_deps_cache
      - run:
          name: Install dependencies
          command: yarn
      - *save_deps_cache
      - persist_to_workspace:
          root: *workspace_root
          paths: ./

  # Runs unit tests.
  unit-test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run unit tests
          command: yarn test:ci

  # Runs formatter and linter.
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run formatter
          command: yarn format
      - run:
          name: Run linter
          command: yarn lint

  # Builds the artifact.
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build project
          command: yarn build
  # Build storybook and upload to S3
  deploy:
    <<: *defaults
    steps:
      - *attach_workspace
      - *install_pip
      - *install_awscli
      - run:
          name: Build storybook
          command: yarn build-storybook
      - run:
          name: Sync to S3
          command: aws s3 sync ./storybook-static/ s3://stardust.tillersystems.com/ --acl public-read

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WORKFLOWS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

workflows:
  version: 2

  # Triggered at every push.
  # Tests, formats and lints source code.
  # Builds the artifact for pushes to master.
  push:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - unit-test:
          requires:
            - setup
      - build:
          requires:
            - lint
            - unit-test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  # Triggered every night.
  # Tests, formats and lints the source code, builds the artifact and deploys it to staging.
  nightly:
    triggers:
      - schedule:
          cron: '50 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - unit-test:
          requires:
            - setup
      - build:
          requires:
            - lint
            - unit-test
